name: Playwright Docker Compose Tests

on:
  push:
    branches:
      - main
      - master

  pull_request:
    branches:
      - main
      - master

jobs:
  playwright-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Playwright Tests using Docker Compose
        run: docker compose up --build --abort-on-container-exit

      - name: Stop Containers
        if: always()
        run: docker compose down

      - name: Upload Playwright Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/